# Generated by Django 3.2 on 2021-05-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=1000)),
                ('last_name', models.CharField(max_length=1000)),
                ('date_of_birth', models.DateField()),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_by', models.CharField(max_length=1000)),
                ('last_updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
