# Generated by Django 3.2 on 2021-05-02 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210502_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_updated_by',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_updated_on',
        ),
    ]
